// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNoteActivity = `-- name: GetNoteActivity :many
SELECT created_at, updated_at FROM notes
WHERE user_id = $1 AND created_at >= $2
`

type GetNoteActivityParams struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetNoteActivityRow struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetNoteActivity(ctx context.Context, arg GetNoteActivityParams) ([]GetNoteActivityRow, error) {
	rows, err := q.db.Query(ctx, getNoteActivity, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNoteActivityRow
	for rows.Next() {
		var i GetNoteActivityRow
		if err := rows.Scan(&i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskActivity = `-- name: GetTaskActivity :many
SELECT created_at, status FROM tasks
WHERE user_id = $1 AND created_at >= $2
`

type GetTaskActivityParams struct {
	UserID    string             `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type GetTaskActivityRow struct {
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Status    interface{}        `json:"status"`
}

func (q *Queries) GetTaskActivity(ctx context.Context, arg GetTaskActivityParams) ([]GetTaskActivityRow, error) {
	rows, err := q.db.Query(ctx, getTaskActivity, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskActivityRow
	for rows.Next() {
		var i GetTaskActivityRow
		if err := rows.Scan(&i.CreatedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
