// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ai_provider_credentials.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIProviderCredential = `-- name: DeleteAIProviderCredential :exec
DELETE FROM user_ai_provider_credentials
WHERE user_id = $1 AND provider = $2
`

type DeleteAIProviderCredentialParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteAIProviderCredential(ctx context.Context, arg DeleteAIProviderCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteAIProviderCredential, arg.UserID, arg.Provider)
	return err
}

const getAIProviderCredential = `-- name: GetAIProviderCredential :one
SELECT user_id, provider, encrypted_api_key, nonce, key_hint, created_at, updated_at
FROM user_ai_provider_credentials
WHERE user_id = $1 AND provider = $2
`

type GetAIProviderCredentialParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetAIProviderCredential(ctx context.Context, arg GetAIProviderCredentialParams) (UserAiProviderCredential, error) {
	row := q.db.QueryRow(ctx, getAIProviderCredential, arg.UserID, arg.Provider)
	var i UserAiProviderCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.EncryptedApiKey,
		&i.Nonce,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIProviderCredentials = `-- name: ListAIProviderCredentials :many
SELECT user_id, provider, key_hint, created_at, updated_at
FROM user_ai_provider_credentials
WHERE user_id = $1
ORDER BY provider
`

type ListAIProviderCredentialsRow struct {
	UserID    string             `json:"user_id"`
	Provider  string             `json:"provider"`
	KeyHint   string             `json:"key_hint"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAIProviderCredentials(ctx context.Context, userID string) ([]ListAIProviderCredentialsRow, error) {
	rows, err := q.db.Query(ctx, listAIProviderCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIProviderCredentialsRow
	for rows.Next() {
		var i ListAIProviderCredentialsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.KeyHint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAIProviderCredential = `-- name: UpsertAIProviderCredential :one
INSERT INTO user_ai_provider_credentials (
    user_id,
    provider,
    encrypted_api_key,
    nonce,
    key_hint
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, provider) DO UPDATE SET
    encrypted_api_key = EXCLUDED.encrypted_api_key,
    nonce = EXCLUDED.nonce,
    key_hint = EXCLUDED.key_hint,
    updated_at = now()
RETURNING user_id, provider, encrypted_api_key, nonce, key_hint, created_at, updated_at
`

type UpsertAIProviderCredentialParams struct {
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	EncryptedApiKey []byte `json:"encrypted_api_key"`
	Nonce           []byte `json:"nonce"`
	KeyHint         string `json:"key_hint"`
}

func (q *Queries) UpsertAIProviderCredential(ctx context.Context, arg UpsertAIProviderCredentialParams) (UserAiProviderCredential, error) {
	row := q.db.QueryRow(ctx, upsertAIProviderCredential,
		arg.UserID,
		arg.Provider,
		arg.EncryptedApiKey,
		arg.Nonce,
		arg.KeyHint,
	)
	var i UserAiProviderCredential
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.EncryptedApiKey,
		&i.Nonce,
		&i.KeyHint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
