// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: content.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const countContent = `-- name: CountContent :one
SELECT count(*) FROM mindmap_content
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountContent(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countContent, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContent = `-- name: CreateContent :one
INSERT INTO mindmap_content (user_id, source_url, source_type, source_title, processing_status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, source_url, source_type, source_title, processing_status, created_at
`

type CreateContentParams struct {
	UserID      string      `json:"user_id"`
	SourceUrl   pgtype.Text `json:"source_url"`
	SourceType  string      `json:"source_type"`
	SourceTitle pgtype.Text `json:"source_title"`
}

type CreateContentRow struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           string             `json:"user_id"`
	SourceUrl        pgtype.Text        `json:"source_url"`
	SourceType       string             `json:"source_type"`
	SourceTitle      pgtype.Text        `json:"source_title"`
	ProcessingStatus string             `json:"processing_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateContent(ctx context.Context, arg CreateContentParams) (CreateContentRow, error) {
	row := q.db.QueryRow(ctx, createContent,
		arg.UserID,
		arg.SourceUrl,
		arg.SourceType,
		arg.SourceTitle,
	)
	var i CreateContentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceTitle,
		&i.ProcessingStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, user_id, source_url, source_type, source_title, source_thumbnail_url,
       extracted_text, visual_description, summary, tags, key_topics,
       summary_provider, embedding_provider, embedding_model,
       media_key, processing_status, processing_error,
       created_at, updated_at
FROM mindmap_content
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetContentByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetContentByIDRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             string             `json:"user_id"`
	SourceUrl          pgtype.Text        `json:"source_url"`
	SourceType         string             `json:"source_type"`
	SourceTitle        pgtype.Text        `json:"source_title"`
	SourceThumbnailUrl pgtype.Text        `json:"source_thumbnail_url"`
	ExtractedText      pgtype.Text        `json:"extracted_text"`
	VisualDescription  pgtype.Text        `json:"visual_description"`
	Summary            pgtype.Text        `json:"summary"`
	Tags               []string           `json:"tags"`
	KeyTopics          []string           `json:"key_topics"`
	SummaryProvider    pgtype.Text        `json:"summary_provider"`
	EmbeddingProvider  pgtype.Text        `json:"embedding_provider"`
	EmbeddingModel     pgtype.Text        `json:"embedding_model"`
	MediaKey           pgtype.Text        `json:"media_key"`
	ProcessingStatus   string             `json:"processing_status"`
	ProcessingError    pgtype.Text        `json:"processing_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContentByID(ctx context.Context, arg GetContentByIDParams) (GetContentByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByID, arg.ID, arg.UserID)
	var i GetContentByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceUrl,
		&i.SourceType,
		&i.SourceTitle,
		&i.SourceThumbnailUrl,
		&i.ExtractedText,
		&i.VisualDescription,
		&i.Summary,
		&i.Tags,
		&i.KeyTopics,
		&i.SummaryProvider,
		&i.EmbeddingProvider,
		&i.EmbeddingModel,
		&i.MediaKey,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isContentDeleted = `-- name: IsContentDeleted :one
SELECT deleted_at IS NOT NULL AS is_deleted
FROM mindmap_content
WHERE id = $1
`

func (q *Queries) IsContentDeleted(ctx context.Context, id pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, isContentDeleted, id)
	var is_deleted interface{}
	err := row.Scan(&is_deleted)
	return is_deleted, err
}

const listContent = `-- name: ListContent :many
SELECT id, user_id, source_url, source_type, source_title, source_thumbnail_url,
       summary, tags, key_topics, media_key,
       processing_status, processing_error,
       created_at, updated_at
FROM mindmap_content
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContentParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListContentRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             string             `json:"user_id"`
	SourceUrl          pgtype.Text        `json:"source_url"`
	SourceType         string             `json:"source_type"`
	SourceTitle        pgtype.Text        `json:"source_title"`
	SourceThumbnailUrl pgtype.Text        `json:"source_thumbnail_url"`
	Summary            pgtype.Text        `json:"summary"`
	Tags               []string           `json:"tags"`
	KeyTopics          []string           `json:"key_topics"`
	MediaKey           pgtype.Text        `json:"media_key"`
	ProcessingStatus   string             `json:"processing_status"`
	ProcessingError    pgtype.Text        `json:"processing_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContent(ctx context.Context, arg ListContentParams) ([]ListContentRow, error) {
	rows, err := q.db.Query(ctx, listContent, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentRow
	for rows.Next() {
		var i ListContentRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SourceUrl,
			&i.SourceType,
			&i.SourceTitle,
			&i.SourceThumbnailUrl,
			&i.Summary,
			&i.Tags,
			&i.KeyTopics,
			&i.MediaKey,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteContent = `-- name: SoftDeleteContent :exec
UPDATE mindmap_content
SET deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteContentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteContent(ctx context.Context, arg SoftDeleteContentParams) error {
	_, err := q.db.Exec(ctx, softDeleteContent, arg.ID, arg.UserID)
	return err
}

const updateContentEmbedding = `-- name: UpdateContentEmbedding :exec
UPDATE mindmap_content
SET embedding = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateContentEmbeddingParams struct {
	ID        pgtype.UUID     `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateContentEmbedding(ctx context.Context, arg UpdateContentEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateContentEmbedding, arg.ID, arg.Embedding)
	return err
}

const updateContentResults = `-- name: UpdateContentResults :exec
UPDATE mindmap_content
SET extracted_text = $2,
    visual_description = $3,
    summary = $4,
    tags = $5,
    key_topics = $6,
    source_title = COALESCE($7, source_title),
    summary_provider = $8,
    embedding_provider = $9,
    embedding_model = $10,
    media_key = COALESCE($11, media_key),
    processing_status = 'completed',
    processing_error = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateContentResultsParams struct {
	ID                pgtype.UUID `json:"id"`
	ExtractedText     pgtype.Text `json:"extracted_text"`
	VisualDescription pgtype.Text `json:"visual_description"`
	Summary           pgtype.Text `json:"summary"`
	Tags              []string    `json:"tags"`
	KeyTopics         []string    `json:"key_topics"`
	SourceTitle       pgtype.Text `json:"source_title"`
	SummaryProvider   pgtype.Text `json:"summary_provider"`
	EmbeddingProvider pgtype.Text `json:"embedding_provider"`
	EmbeddingModel    pgtype.Text `json:"embedding_model"`
	MediaKey          pgtype.Text `json:"media_key"`
}

func (q *Queries) UpdateContentResults(ctx context.Context, arg UpdateContentResultsParams) error {
	_, err := q.db.Exec(ctx, updateContentResults,
		arg.ID,
		arg.ExtractedText,
		arg.VisualDescription,
		arg.Summary,
		arg.Tags,
		arg.KeyTopics,
		arg.SourceTitle,
		arg.SummaryProvider,
		arg.EmbeddingProvider,
		arg.EmbeddingModel,
		arg.MediaKey,
	)
	return err
}

const updateContentStatus = `-- name: UpdateContentStatus :exec
UPDATE mindmap_content
SET processing_status = $2,
    processing_error = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateContentStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	ProcessingStatus string      `json:"processing_status"`
	ProcessingError  pgtype.Text `json:"processing_error"`
}

func (q *Queries) UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) error {
	_, err := q.db.Exec(ctx, updateContentStatus, arg.ID, arg.ProcessingStatus, arg.ProcessingError)
	return err
}
