// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countConversations = `-- name: CountConversations :one
SELECT count(*) FROM conversations
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountConversations(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countConversations, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, provider, model, project_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, title, provider, model, project_id, created_at, updated_at
`

type CreateConversationParams struct {
	UserID    string      `json:"user_id"`
	Provider  string      `json:"provider"`
	Model     string      `json:"model"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type CreateConversationRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.UserID,
		arg.Provider,
		arg.Model,
		arg.ProjectID,
	)
	var i CreateConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Provider,
		&i.Model,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, provider, model, project_id, created_at, updated_at
FROM conversations
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetConversationRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Provider,
		&i.Model,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, provider, model, project_id, created_at, updated_at
FROM conversations
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListConversationsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Provider,
			&i.Model,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteConversation = `-- name: SoftDeleteConversation :exec
UPDATE conversations
SET deleted_at = now()
WHERE id = $1 AND user_id = $2
`

type SoftDeleteConversationParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteConversation(ctx context.Context, arg SoftDeleteConversationParams) error {
	_, err := q.db.Exec(ctx, softDeleteConversation, arg.ID, arg.UserID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}

const updateConversationConfiguration = `-- name: UpdateConversationConfiguration :one
UPDATE conversations
SET provider = $3,
    model = $4,
    project_id = $5,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, title, provider, model, project_id, created_at, updated_at
`

type UpdateConversationConfigurationParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    string      `json:"user_id"`
	Provider  string      `json:"provider"`
	Model     string      `json:"model"`
	ProjectID pgtype.UUID `json:"project_id"`
}

type UpdateConversationConfigurationRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	ProjectID pgtype.UUID        `json:"project_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateConversationConfiguration(ctx context.Context, arg UpdateConversationConfigurationParams) (UpdateConversationConfigurationRow, error) {
	row := q.db.QueryRow(ctx, updateConversationConfiguration,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.Model,
		arg.ProjectID,
	)
	var i UpdateConversationConfigurationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Provider,
		&i.Model,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :exec
UPDATE conversations
SET title = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
`

type UpdateConversationTitleParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
	Title  pgtype.Text `json:"title"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error {
	_, err := q.db.Exec(ctx, updateConversationTitle, arg.ID, arg.UserID, arg.Title)
	return err
}
