// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCompletedGoals = `-- name: ArchiveCompletedGoals :one
WITH updated AS (
    UPDATE mindmap_goal SET status = 'archived', updated_at = CURRENT_TIMESTAMP
    WHERE user_id = $1 AND status = 'completed'
    RETURNING id
)
SELECT COUNT(*)::int FROM updated
`

func (q *Queries) ArchiveCompletedGoals(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, archiveCompletedGoals, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const archiveGoalsByProject = `-- name: ArchiveGoalsByProject :exec
UPDATE mindmap_goal SET status = 'archived', updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type ArchiveGoalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ArchiveGoalsByProject(ctx context.Context, arg ArchiveGoalsByProjectParams) error {
	_, err := q.db.Exec(ctx, archiveGoalsByProject, arg.ProjectID, arg.UserID)
	return err
}

const countGoals = `-- name: CountGoals :one
SELECT COUNT(*)::int FROM mindmap_goal
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR status != 'archived')
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
`

type CountGoalsParams struct {
	UserID  string      `json:"user_id"`
	Column2 bool        `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) CountGoals(ctx context.Context, arg CountGoalsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countGoals, arg.UserID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGoal = `-- name: CreateGoal :exec
INSERT INTO mindmap_goal (title, description, status, priority, impact, position, user_id, project_id, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateGoalParams struct {
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      interface{}        `json:"status"`
	Priority    interface{}        `json:"priority"`
	Impact      interface{}        `json:"impact"`
	Position    int32              `json:"position"`
	UserID      string             `json:"user_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) error {
	_, err := q.db.Exec(ctx, createGoal,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Impact,
		arg.Position,
		arg.UserID,
		arg.ProjectID,
		arg.CompletedAt,
	)
	return err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT g.id, g.title, g.description, g.status, g.priority, g.impact, g.position,
       g.created_at, g.updated_at, g.completed_at, g.deleted_at, g.user_id, g.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM mindmap_goal g
LEFT JOIN mindmap_project p ON g.project_id = p.id
WHERE g.id = $1 AND g.user_id = $2
`

type GetGoalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetGoalByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         pgtype.Text        `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	Priority      interface{}        `json:"priority"`
	Impact        interface{}        `json:"impact"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (GetGoalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoalByID, arg.ID, arg.UserID)
	var i GetGoalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Impact,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.ProjectID,
		&i.ProjectRefID,
		&i.ProjectName,
		&i.ProjectStatus,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT g.id, g.title, g.description, g.status, g.priority, g.impact, g.position,
       g.created_at, g.updated_at, g.completed_at, g.deleted_at, g.user_id, g.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM mindmap_goal g
LEFT JOIN mindmap_project p ON g.project_id = p.id
WHERE g.user_id = $1
  AND g.deleted_at IS NULL
  AND ($2::boolean OR g.status != 'archived')
  AND ($3::uuid IS NULL OR g.project_id = $3::uuid)
ORDER BY g.position ASC, g.priority ASC, g.created_at DESC
`

type ListGoalsParams struct {
	UserID  string      `json:"user_id"`
	Column2 bool        `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

type ListGoalsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         pgtype.Text        `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	Priority      interface{}        `json:"priority"`
	Impact        interface{}        `json:"impact"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]ListGoalsRow, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsRow
	for rows.Next() {
		var i ListGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
			&i.ProjectRefID,
			&i.ProjectName,
			&i.ProjectStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedGoals = `-- name: ListUnassignedGoals :many
SELECT id, title, description, status, priority, impact, position, created_at, updated_at, completed_at, deleted_at, user_id, project_id FROM mindmap_goal
WHERE user_id = $1 AND project_id IS NULL AND deleted_at IS NULL AND status != 'archived'
ORDER BY position ASC, priority ASC, created_at DESC
`

func (q *Queries) ListUnassignedGoals(ctx context.Context, userID string) ([]MindmapGoal, error) {
	rows, err := q.db.Query(ctx, listUnassignedGoals, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapGoal
	for rows.Next() {
		var i MindmapGoal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGoals = `-- name: SearchGoals :many
SELECT id, title, description, status, priority, impact, position, created_at, updated_at, completed_at, deleted_at, user_id, project_id FROM mindmap_goal
WHERE user_id = $1 AND deleted_at IS NULL AND status != 'archived'
  AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC LIMIT 5
`

type SearchGoalsParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchGoals(ctx context.Context, arg SearchGoalsParams) ([]MindmapGoal, error) {
	rows, err := q.db.Query(ctx, searchGoals, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapGoal
	for rows.Next() {
		var i MindmapGoal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGoal = `-- name: SoftDeleteGoal :exec
UPDATE mindmap_goal SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type SoftDeleteGoalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteGoal(ctx context.Context, arg SoftDeleteGoalParams) error {
	_, err := q.db.Exec(ctx, softDeleteGoal, arg.ID, arg.UserID)
	return err
}

const softDeleteGoalsByProject = `-- name: SoftDeleteGoalsByProject :exec
UPDATE mindmap_goal SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type SoftDeleteGoalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) SoftDeleteGoalsByProject(ctx context.Context, arg SoftDeleteGoalsByProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteGoalsByProject, arg.ProjectID, arg.UserID)
	return err
}

const updateGoal = `-- name: UpdateGoal :exec
UPDATE mindmap_goal SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    priority = COALESCE($6, priority),
    impact = COALESCE($7, impact),
    position = COALESCE($8, position),
    project_id = $9,
    completed_at = $10,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateGoalParams struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      string             `json:"user_id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      interface{}        `json:"status"`
	Priority    interface{}        `json:"priority"`
	Impact      interface{}        `json:"impact"`
	Position    int32              `json:"position"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) error {
	_, err := q.db.Exec(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Impact,
		arg.Position,
		arg.ProjectID,
		arg.CompletedAt,
	)
	return err
}

const updateGoalPosition = `-- name: UpdateGoalPosition :exec
UPDATE mindmap_goal SET
    position = $3,
    status = COALESCE($4, status),
    completed_at = CASE
        WHEN $4 = 'completed' THEN CURRENT_TIMESTAMP
        WHEN $4 = 'archived' THEN completed_at
        WHEN $4 IS NOT NULL THEN NULL
        ELSE completed_at
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateGoalPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   string      `json:"user_id"`
	Position int32       `json:"position"`
	Status   interface{} `json:"status"`
}

func (q *Queries) UpdateGoalPosition(ctx context.Context, arg UpdateGoalPositionParams) error {
	_, err := q.db.Exec(ctx, updateGoalPosition,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.Status,
	)
	return err
}
