// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habit_tracker.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getHabitCompletionStats = `-- name: GetHabitCompletionStats :many
SELECT h.id AS habit_id,
       h.title AS habit_title,
       COUNT(ht.id) AS completion_count,
       MIN(ht.date) AS first_completion,
       MAX(ht.date) AS last_completion
FROM mindmap_habit h
LEFT JOIN mindmap_habit_tracker ht
  ON h.id = ht.habit_id
  AND ht.date >= $1
  AND ht.date <= $2
WHERE h.user_id = $3
GROUP BY h.id, h.title
ORDER BY completion_count DESC
`

type GetHabitCompletionStatsParams struct {
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	UserID    string      `json:"user_id"`
}

type GetHabitCompletionStatsRow struct {
	HabitID         pgtype.UUID `json:"habit_id"`
	HabitTitle      pgtype.Text `json:"habit_title"`
	CompletionCount int64       `json:"completion_count"`
	FirstCompletion interface{} `json:"first_completion"`
	LastCompletion  interface{} `json:"last_completion"`
}

func (q *Queries) GetHabitCompletionStats(ctx context.Context, arg GetHabitCompletionStatsParams) ([]GetHabitCompletionStatsRow, error) {
	rows, err := q.db.Query(ctx, getHabitCompletionStats, arg.StartDate, arg.EndDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHabitCompletionStatsRow
	for rows.Next() {
		var i GetHabitCompletionStatsRow
		if err := rows.Scan(
			&i.HabitID,
			&i.HabitTitle,
			&i.CompletionCount,
			&i.FirstCompletion,
			&i.LastCompletion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isHabitTrackedOnDate = `-- name: IsHabitTrackedOnDate :one
SELECT EXISTS(
  SELECT 1 FROM mindmap_habit_tracker
  WHERE habit_id = $1 AND user_id = $2 AND date = $3
) AS tracked
`

type IsHabitTrackedOnDateParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	UserID  string      `json:"user_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) IsHabitTrackedOnDate(ctx context.Context, arg IsHabitTrackedOnDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, isHabitTrackedOnDate, arg.HabitID, arg.UserID, arg.Date)
	var tracked bool
	err := row.Scan(&tracked)
	return tracked, err
}

const listHabitTrackerRecords = `-- name: ListHabitTrackerRecords :many
SELECT id, habit_id, status, date, created_at, updated_at, user_id FROM mindmap_habit_tracker WHERE user_id = $1
`

func (q *Queries) ListHabitTrackerRecords(ctx context.Context, userID string) ([]MindmapHabitTracker, error) {
	rows, err := q.db.Query(ctx, listHabitTrackerRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapHabitTracker
	for rows.Next() {
		var i MindmapHabitTracker
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackHabit = `-- name: TrackHabit :one
INSERT INTO mindmap_habit_tracker (habit_id, user_id, status, date)
VALUES ($1, $2, 'completed', $3)
ON CONFLICT (habit_id, user_id, date) DO UPDATE SET status = 'completed', updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type TrackHabitParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	UserID  string      `json:"user_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) TrackHabit(ctx context.Context, arg TrackHabitParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, trackHabit, arg.HabitID, arg.UserID, arg.Date)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const untrackHabit = `-- name: UntrackHabit :exec
DELETE FROM mindmap_habit_tracker WHERE habit_id = $1 AND user_id = $2 AND date = $3
`

type UntrackHabitParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	UserID  string      `json:"user_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) UntrackHabit(ctx context.Context, arg UntrackHabitParams) error {
	_, err := q.db.Exec(ctx, untrackHabit, arg.HabitID, arg.UserID, arg.Date)
	return err
}
