// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habit_tracker.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listHabitTrackerRecords = `-- name: ListHabitTrackerRecords :many
SELECT id, habit_id, status, date, created_at, updated_at, user_id FROM mindmap_habit_tracker WHERE user_id = $1
`

func (q *Queries) ListHabitTrackerRecords(ctx context.Context, userID string) ([]MindmapHabitTracker, error) {
	rows, err := q.db.Query(ctx, listHabitTrackerRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapHabitTracker
	for rows.Next() {
		var i MindmapHabitTracker
		if err := rows.Scan(
			&i.ID,
			&i.HabitID,
			&i.Status,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackHabit = `-- name: TrackHabit :one
INSERT INTO mindmap_habit_tracker (habit_id, user_id, status, date)
VALUES ($1, $2, 'completed', $3)
ON CONFLICT (habit_id, user_id, date) DO UPDATE SET status = 'completed', updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type TrackHabitParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	UserID  string      `json:"user_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) TrackHabit(ctx context.Context, arg TrackHabitParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, trackHabit, arg.HabitID, arg.UserID, arg.Date)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const untrackHabit = `-- name: UntrackHabit :exec
DELETE FROM mindmap_habit_tracker WHERE habit_id = $1 AND user_id = $2 AND date = $3
`

type UntrackHabitParams struct {
	HabitID pgtype.UUID `json:"habit_id"`
	UserID  string      `json:"user_id"`
	Date    pgtype.Date `json:"date"`
}

func (q *Queries) UntrackHabit(ctx context.Context, arg UntrackHabitParams) error {
	_, err := q.db.Exec(ctx, untrackHabit, arg.HabitID, arg.UserID, arg.Date)
	return err
}
