// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkHabitTitleExists = `-- name: CheckHabitTitleExists :one
SELECT EXISTS(
    SELECT 1 FROM mindmap_habit
    WHERE user_id = $1 AND title = $2 AND deleted_at IS NULL
    AND ($3::uuid IS NULL OR id != $3::uuid)
) AS "exists"
`

type CheckHabitTitleExistsParams struct {
	UserID  string      `json:"user_id"`
	Title   pgtype.Text `json:"title"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) CheckHabitTitleExists(ctx context.Context, arg CheckHabitTitleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkHabitTitleExists, arg.UserID, arg.Title, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createHabit = `-- name: CreateHabit :exec
INSERT INTO mindmap_habit (title, description, frequency, user_id)
VALUES ($1, $2, $3, $4)
`

type CreateHabitParams struct {
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Frequency   interface{} `json:"frequency"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) error {
	_, err := q.db.Exec(ctx, createHabit,
		arg.Title,
		arg.Description,
		arg.Frequency,
		arg.UserID,
	)
	return err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM mindmap_habit WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) error {
	_, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	return err
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, title, description, frequency, created_at, updated_at, deleted_at, user_id FROM mindmap_habit WHERE id = $1 AND user_id = $2
`

type GetHabitByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) GetHabitByID(ctx context.Context, arg GetHabitByIDParams) (MindmapHabit, error) {
	row := q.db.QueryRow(ctx, getHabitByID, arg.ID, arg.UserID)
	var i MindmapHabit
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
	)
	return i, err
}

const listHabits = `-- name: ListHabits :many
SELECT id, title, description, frequency, created_at, updated_at, deleted_at, user_id FROM mindmap_habit WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListHabits(ctx context.Context, userID string) ([]MindmapHabit, error) {
	rows, err := q.db.Query(ctx, listHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapHabit
	for rows.Next() {
		var i MindmapHabit
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchHabits = `-- name: SearchHabits :many
SELECT id, title, description, frequency, created_at, updated_at, deleted_at, user_id FROM mindmap_habit
WHERE user_id = $1 AND deleted_at IS NULL AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC LIMIT 5
`

type SearchHabitsParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchHabits(ctx context.Context, arg SearchHabitsParams) ([]MindmapHabit, error) {
	rows, err := q.db.Query(ctx, searchHabits, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapHabit
	for rows.Next() {
		var i MindmapHabit
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :exec
UPDATE mindmap_habit SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    frequency = COALESCE($5, frequency),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateHabitParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      string      `json:"user_id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Frequency   interface{} `json:"frequency"`
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) error {
	_, err := q.db.Exec(ctx, updateHabit,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Frequency,
	)
	return err
}
