// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE mindmap_jobs
SET status = 'completed',
    completed_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO mindmap_jobs (content_id, user_id, content_type, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id
`

type CreateJobParams struct {
	ContentID   pgtype.UUID `json:"content_id"`
	UserID      string      `json:"user_id"`
	ContentType string      `json:"content_type"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ContentID, arg.UserID, arg.ContentType)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :exec
UPDATE mindmap_jobs
SET status = 'failed',
    last_error = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type FailJobParams struct {
	ID        pgtype.UUID `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastError)
	return err
}

const getJobByContentID = `-- name: GetJobByContentID :one
SELECT id, content_id, user_id, content_type, status, current_step,
       attempt_count, max_attempts, last_error, next_retry_at,
       step_results, started_at, completed_at, created_at, updated_at
FROM mindmap_jobs
WHERE content_id = $1
`

func (q *Queries) GetJobByContentID(ctx context.Context, contentID pgtype.UUID) (MindmapJob, error) {
	row := q.db.QueryRow(ctx, getJobByContentID, contentID)
	var i MindmapJob
	err := row.Scan(
		&i.ID,
		&i.ContentID,
		&i.UserID,
		&i.ContentType,
		&i.Status,
		&i.CurrentStep,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastError,
		&i.NextRetryAt,
		&i.StepResults,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startJob = `-- name: StartJob :exec
UPDATE mindmap_jobs
SET status = 'processing',
    started_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) StartJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, startJob, id)
	return err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE mindmap_jobs
SET status = $2,
    current_step = $3,
    last_error = $4,
    attempt_count = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateJobStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	CurrentStep  pgtype.Text `json:"current_step"`
	LastError    pgtype.Text `json:"last_error"`
	AttemptCount int32       `json:"attempt_count"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateJobStatus,
		arg.ID,
		arg.Status,
		arg.CurrentStep,
		arg.LastError,
		arg.AttemptCount,
	)
	return err
}

const updateJobStepResults = `-- name: UpdateJobStepResults :exec
UPDATE mindmap_jobs
SET step_results = $2,
    current_step = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateJobStepResultsParams struct {
	ID          pgtype.UUID `json:"id"`
	StepResults []byte      `json:"step_results"`
	CurrentStep pgtype.Text `json:"current_step"`
}

func (q *Queries) UpdateJobStepResults(ctx context.Context, arg UpdateJobStepResultsParams) error {
	_, err := q.db.Exec(ctx, updateJobStepResults, arg.ID, arg.StepResults, arg.CurrentStep)
	return err
}
