// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveJournalsByProject = `-- name: ArchiveJournalsByProject :exec
UPDATE mindmap_journal SET archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type ArchiveJournalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ArchiveJournalsByProject(ctx context.Context, arg ArchiveJournalsByProjectParams) error {
	_, err := q.db.Exec(ctx, archiveJournalsByProject, arg.ProjectID, arg.UserID)
	return err
}

const checkJournalTitleExists = `-- name: CheckJournalTitleExists :one
SELECT EXISTS(
    SELECT 1 FROM mindmap_journal
    WHERE user_id = $1 AND title = $2 AND deleted_at IS NULL
    AND ($3::uuid IS NULL OR id != $3::uuid)
) AS "exists"
`

type CheckJournalTitleExistsParams struct {
	UserID  string      `json:"user_id"`
	Title   string      `json:"title"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) CheckJournalTitleExists(ctx context.Context, arg CheckJournalTitleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkJournalTitleExists, arg.UserID, arg.Title, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countJournals = `-- name: CountJournals :one
SELECT COUNT(*)::int FROM mindmap_journal WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountJournals(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countJournals, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createJournal = `-- name: CreateJournal :exec
INSERT INTO mindmap_journal (title, content, user_id, project_id)
VALUES ($1, $2, $3, $4)
`

type CreateJournalParams struct {
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	UserID    string      `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) error {
	_, err := q.db.Exec(ctx, createJournal,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.ProjectID,
	)
	return err
}

const deleteJournal = `-- name: DeleteJournal :exec
DELETE FROM mindmap_journal WHERE id = $1 AND user_id = $2
`

type DeleteJournalParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteJournal(ctx context.Context, arg DeleteJournalParams) error {
	_, err := q.db.Exec(ctx, deleteJournal, arg.ID, arg.UserID)
	return err
}

const getJournalByID = `-- name: GetJournalByID :one
SELECT j.id, j.title, j.content, j.type, j.source,
       j.created_at, j.updated_at, j.deleted_at, j.archived_at, j.user_id, j.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM mindmap_journal j
LEFT JOIN mindmap_project p ON j.project_id = p.id
WHERE j.id = $1 AND j.user_id = $2
`

type GetJournalByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetJournalByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Type          interface{}        `json:"type"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) GetJournalByID(ctx context.Context, arg GetJournalByIDParams) (GetJournalByIDRow, error) {
	row := q.db.QueryRow(ctx, getJournalByID, arg.ID, arg.UserID)
	var i GetJournalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.ProjectID,
		&i.ProjectRefID,
		&i.ProjectName,
		&i.ProjectStatus,
	)
	return i, err
}

const listJournals = `-- name: ListJournals :many
SELECT j.id, j.title, j.content, j.type, j.source,
       j.created_at, j.updated_at, j.deleted_at, j.archived_at, j.user_id, j.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM mindmap_journal j
LEFT JOIN mindmap_project p ON j.project_id = p.id
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND ($2::uuid IS NULL OR j.project_id = $2::uuid)
ORDER BY j.updated_at DESC
`

type ListJournalsParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

type ListJournalsRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Type          interface{}        `json:"type"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) ListJournals(ctx context.Context, arg ListJournalsParams) ([]ListJournalsRow, error) {
	rows, err := q.db.Query(ctx, listJournals, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJournalsRow
	for rows.Next() {
		var i ListJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ArchivedAt,
			&i.UserID,
			&i.ProjectID,
			&i.ProjectRefID,
			&i.ProjectName,
			&i.ProjectStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchJournals = `-- name: SearchJournals :many
SELECT id, title, content, type, source, created_at, updated_at, user_id, project_id, deleted_at, archived_at FROM mindmap_journal
WHERE user_id = $1 AND deleted_at IS NULL AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC LIMIT 5
`

type SearchJournalsParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchJournals(ctx context.Context, arg SearchJournalsParams) ([]MindmapJournal, error) {
	rows, err := q.db.Query(ctx, searchJournals, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapJournal
	for rows.Next() {
		var i MindmapJournal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ProjectID,
			&i.DeletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteJournalsByProject = `-- name: SoftDeleteJournalsByProject :exec
UPDATE mindmap_journal SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type SoftDeleteJournalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) SoftDeleteJournalsByProject(ctx context.Context, arg SoftDeleteJournalsByProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteJournalsByProject, arg.ProjectID, arg.UserID)
	return err
}

const updateJournal = `-- name: UpdateJournal :exec
UPDATE mindmap_journal SET
    title = COALESCE($3, title),
    content = COALESCE($4, content),
    project_id = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateJournalParams struct {
	ID        pgtype.UUID `json:"id"`
	UserID    string      `json:"user_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateJournal(ctx context.Context, arg UpdateJournalParams) error {
	_, err := q.db.Exec(ctx, updateJournal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ProjectID,
	)
	return err
}

const upsertJournalFromSync = `-- name: UpsertJournalFromSync :exec
INSERT INTO mindmap_journal (title, content, user_id, source, type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, title) WHERE deleted_at IS NULL
DO UPDATE SET content = EXCLUDED.content, updated_at = CURRENT_TIMESTAMP
`

type UpsertJournalFromSyncParams struct {
	Title   string      `json:"title"`
	Content string      `json:"content"`
	UserID  string      `json:"user_id"`
	Source  string      `json:"source"`
	Type    interface{} `json:"type"`
}

func (q *Queries) UpsertJournalFromSync(ctx context.Context, arg UpsertJournalFromSyncParams) error {
	_, err := q.db.Exec(ctx, upsertJournalFromSync,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Source,
		arg.Type,
	)
	return err
}
