// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConnectedNotes = `-- name: GetConnectedNotes :many
SELECT j.id, j.title, j.content, j.updated_at, j.created_at
FROM notes j
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND j.content LIKE $2
ORDER BY j.updated_at DESC NULLS LAST
LIMIT 10
`

type GetConnectedNotesParams struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

type GetConnectedNotesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Find notes whose content contains a mention of the given entity.
// mention_pattern should be like '%data-id="task:UUID"%' or '%data-id="note:UUID"%'.
func (q *Queries) GetConnectedNotes(ctx context.Context, arg GetConnectedNotesParams) ([]GetConnectedNotesRow, error) {
	rows, err := q.db.Query(ctx, getConnectedNotes, arg.UserID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectedNotesRow
	for rows.Next() {
		var i GetConnectedNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
