// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConnectedHabitIDs = `-- name: GetConnectedHabitIDs :many
SELECT DISTINCT (regexp_matches(j.content, 'data-id="habit:([0-9a-f\-]{36})"', 'g'))[1]::uuid AS habit_id
FROM mindmap_journal j
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND j.content LIKE $2
`

type GetConnectedHabitIDsParams struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

// Find habit UUIDs mentioned in notes that also mention a given goal.
// goal_pattern should be like '%data-id="goal:UUID"%'.
// Returns distinct habit IDs extracted via regex from note content.
func (q *Queries) GetConnectedHabitIDs(ctx context.Context, arg GetConnectedHabitIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getConnectedHabitIDs, arg.UserID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var habit_id pgtype.UUID
		if err := rows.Scan(&habit_id); err != nil {
			return nil, err
		}
		items = append(items, habit_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConnectedNotes = `-- name: GetConnectedNotes :many
SELECT j.id, j.title, j.content, j.updated_at, j.created_at
FROM mindmap_journal j
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND j.content LIKE $2
ORDER BY j.updated_at DESC NULLS LAST
LIMIT 10
`

type GetConnectedNotesParams struct {
	UserID  string `json:"user_id"`
	Content string `json:"content"`
}

type GetConnectedNotesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Find notes/journals whose content contains a mention of the given entity.
// mention_pattern should be like '%data-id="goal:UUID"%' or '%data-id="habit:UUID"%'.
func (q *Queries) GetConnectedNotes(ctx context.Context, arg GetConnectedNotesParams) ([]GetConnectedNotesRow, error) {
	rows, err := q.db.Query(ctx, getConnectedNotes, arg.UserID, arg.Content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConnectedNotesRow
	for rows.Next() {
		var i GetConnectedNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitsByIDs = `-- name: GetHabitsByIDs :many
SELECT id, title, description, frequency, created_at, updated_at, deleted_at, user_id FROM mindmap_habit
WHERE user_id = $1
  AND deleted_at IS NULL
  AND id = ANY($2::uuid[])
`

type GetHabitsByIDsParams struct {
	UserID  string        `json:"user_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

// Fetch habits by a list of IDs for a given user.
func (q *Queries) GetHabitsByIDs(ctx context.Context, arg GetHabitsByIDsParams) ([]MindmapHabit, error) {
	rows, err := q.db.Query(ctx, getHabitsByIDs, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapHabit
	for rows.Next() {
		var i MindmapHabit
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
