// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM mindmap_messages
WHERE conversation_id = $1
`

func (q *Queries) CountMessages(ctx context.Context, conversationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO mindmap_messages (conversation_id, role, content, attachments, tool_calls, tool_call_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, conversation_id, role, content, attachments, tool_calls, tool_call_id, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Role           string      `json:"role"`
	Content        string      `json:"content"`
	Attachments    []byte      `json:"attachments"`
	ToolCalls      []byte      `json:"tool_calls"`
	ToolCallID     pgtype.Text `json:"tool_call_id"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (MindmapMessage, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Attachments,
		arg.ToolCalls,
		arg.ToolCallID,
	)
	var i MindmapMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Attachments,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT id, conversation_id, role, content, attachments, tool_calls, tool_call_id, created_at
FROM mindmap_messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id pgtype.UUID) (MindmapMessage, error) {
	row := q.db.QueryRow(ctx, getMessage, id)
	var i MindmapMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Attachments,
		&i.ToolCalls,
		&i.ToolCallID,
		&i.CreatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, attachments, tool_calls, tool_call_id, created_at
FROM mindmap_messages
WHERE conversation_id = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListMessagesParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]MindmapMessage, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapMessage
	for rows.Next() {
		var i MindmapMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Attachments,
			&i.ToolCalls,
			&i.ToolCallID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
