// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MindmapGoal struct {
	ID          pgtype.UUID        `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      interface{}        `json:"status"`
	Priority    interface{}        `json:"priority"`
	Impact      interface{}        `json:"impact"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UserID      string             `json:"user_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
}

type MindmapHabit struct {
	ID          pgtype.UUID        `json:"id"`
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Frequency   interface{}        `json:"frequency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	UserID      string             `json:"user_id"`
}

type MindmapHabitTracker struct {
	ID        pgtype.UUID        `json:"id"`
	HabitID   pgtype.UUID        `json:"habit_id"`
	Status    interface{}        `json:"status"`
	Date      pgtype.Date        `json:"date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    string             `json:"user_id"`
}

type MindmapJournal struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Type       interface{}        `json:"type"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     string             `json:"user_id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type MindmapJournalGoal struct {
	ID        pgtype.UUID        `json:"id"`
	JournalID pgtype.UUID        `json:"journal_id"`
	GoalID    pgtype.UUID        `json:"goal_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MindmapJournalHabit struct {
	ID        pgtype.UUID        `json:"id"`
	JournalID pgtype.UUID        `json:"journal_id"`
	HabitID   pgtype.UUID        `json:"habit_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MindmapProject struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     string             `json:"created_by"`
	LastUpdatedBy string             `json:"last_updated_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type MindmapRefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MindmapUser struct {
	ID                  string             `json:"id"`
	Name                pgtype.Text        `json:"name"`
	Email               string             `json:"email"`
	EmailVerified       pgtype.Timestamptz `json:"email_verified"`
	Image               pgtype.Text        `json:"image"`
	Xp                  int32              `json:"xp"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
}

type MindmapVerificationToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	Type         string             `json:"type"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Attempts     int32              `json:"attempts"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
