// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Content struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             string             `json:"user_id"`
	SourceUrl          pgtype.Text        `json:"source_url"`
	SourceType         string             `json:"source_type"`
	SourceTitle        pgtype.Text        `json:"source_title"`
	SourceThumbnailUrl pgtype.Text        `json:"source_thumbnail_url"`
	ExtractedText      pgtype.Text        `json:"extracted_text"`
	VisualDescription  pgtype.Text        `json:"visual_description"`
	Summary            pgtype.Text        `json:"summary"`
	Tags               []string           `json:"tags"`
	KeyTopics          []string           `json:"key_topics"`
	Embedding          pgvector.Vector    `json:"embedding"`
	SummaryProvider    pgtype.Text        `json:"summary_provider"`
	EmbeddingProvider  pgtype.Text        `json:"embedding_provider"`
	EmbeddingModel     pgtype.Text        `json:"embedding_model"`
	MediaKey           pgtype.Text        `json:"media_key"`
	ProcessingStatus   string             `json:"processing_status"`
	ProcessingError    pgtype.Text        `json:"processing_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	// Duration in seconds for any time-based content (video, audio)
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	// YouTube thumbnail URL from yt-dlp metadata
	VideoThumbnailUrl pgtype.Text `json:"video_thumbnail_url"`
	// YouTube channel name
	VideoChannel pgtype.Text `json:"video_channel"`
	// captions or whisper — how the transcript was obtained
	TranscriptSource pgtype.Text `json:"transcript_source"`
	// draft until the user finalises the save; committed otherwise
	CommitStatus string `json:"commit_status"`
	// MIME type for stored media (audio/mp4, image/png etc.)
	MediaMime pgtype.Text `json:"media_mime"`
	// Size of the stored media file in bytes
	MediaFileBytes pgtype.Int8 `json:"media_file_bytes"`
	// Source-specific metadata captured by first-class processors, keyed by source_type
	SourceMetadata []byte `json:"source_metadata"`
}

type Conversation struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Title     pgtype.Text        `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Provider  string             `json:"provider"`
	Model     string             `json:"model"`
	ProjectID pgtype.UUID        `json:"project_id"`
}

type Job struct {
	ID           pgtype.UUID        `json:"id"`
	ContentID    pgtype.UUID        `json:"content_id"`
	UserID       string             `json:"user_id"`
	ContentType  string             `json:"content_type"`
	Status       string             `json:"status"`
	CurrentStep  pgtype.Text        `json:"current_step"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	LastError    pgtype.Text        `json:"last_error"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
	StepResults  []byte             `json:"step_results"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Message struct {
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	Attachments    []byte             `json:"attachments"`
	ToolCalls      []byte             `json:"tool_calls"`
	ToolCallID     pgtype.Text        `json:"tool_call_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	Type       interface{}        `json:"type"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	UserID     string             `json:"user_id"`
	ProjectID  pgtype.UUID        `json:"project_id"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type NoteTask struct {
	ID        pgtype.UUID        `json:"id"`
	NoteID    pgtype.UUID        `json:"note_id"`
	TaskID    pgtype.UUID        `json:"task_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID            pgtype.UUID        `json:"id"`
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	StartDate     pgtype.Date        `json:"start_date"`
	EndDate       pgtype.Date        `json:"end_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CreatedBy     string             `json:"created_by"`
	LastUpdatedBy string             `json:"last_updated_by"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Task struct {
	ID               pgtype.UUID        `json:"id"`
	Title            pgtype.Text        `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Status           interface{}        `json:"status"`
	Priority         interface{}        `json:"priority"`
	Impact           interface{}        `json:"impact"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	UserID           string             `json:"user_id"`
	ProjectID        pgtype.UUID        `json:"project_id"`
	ScheduledStartAt pgtype.Timestamptz `json:"scheduled_start_at"`
	ScheduledEndAt   pgtype.Timestamptz `json:"scheduled_end_at"`
}

type User struct {
	ID                  string             `json:"id"`
	Name                pgtype.Text        `json:"name"`
	Email               string             `json:"email"`
	EmailVerified       pgtype.Timestamptz `json:"email_verified"`
	Image               pgtype.Text        `json:"image"`
	OnboardingCompleted bool               `json:"onboarding_completed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	Theme               string             `json:"theme"`
	Font                string             `json:"font"`
	AppearanceTemplate  string             `json:"appearance_template"`
	AccentColor         string             `json:"accent_color"`
	BackgroundColor     string             `json:"background_color"`
	ForegroundColor     string             `json:"foreground_color"`
	Contrast            int32              `json:"contrast"`
	FontSize            int32              `json:"font_size"`
	WeekStartDay        string             `json:"week_start_day"`
	TimeFormat          string             `json:"time_format"`
	TimeZone            string             `json:"time_zone"`
	CodeFont            string             `json:"code_font"`
	Radius              int32              `json:"radius"`
}

type UserAiProviderCredential struct {
	UserID          string             `json:"user_id"`
	Provider        string             `json:"provider"`
	EncryptedApiKey []byte             `json:"encrypted_api_key"`
	Nonce           []byte             `json:"nonce"`
	KeyHint         string             `json:"key_hint"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type VerificationToken struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	Type         string             `json:"type"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Attempts     int32              `json:"attempts"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
