// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveNotesByProject = `-- name: ArchiveNotesByProject :exec
UPDATE notes SET archived_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type ArchiveNotesByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ArchiveNotesByProject(ctx context.Context, arg ArchiveNotesByProjectParams) error {
	_, err := q.db.Exec(ctx, archiveNotesByProject, arg.ProjectID, arg.UserID)
	return err
}

const checkNoteTitleExists = `-- name: CheckNoteTitleExists :one
SELECT EXISTS(
    SELECT 1 FROM notes
    WHERE user_id = $1 AND title = $2 AND deleted_at IS NULL
    AND ($3::uuid IS NULL OR id != $3::uuid)
) AS "exists"
`

type CheckNoteTitleExistsParams struct {
	UserID  string      `json:"user_id"`
	Title   string      `json:"title"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) CheckNoteTitleExists(ctx context.Context, arg CheckNoteTitleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNoteTitleExists, arg.UserID, arg.Title, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countNotes = `-- name: CountNotes :one
SELECT COUNT(*)::int FROM notes WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountNotes(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNotes, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNote = `-- name: CreateNote :exec
INSERT INTO notes (title, content, user_id, project_id)
VALUES ($1, $2, $3, $4)
`

type CreateNoteParams struct {
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	UserID    string      `json:"user_id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) error {
	_, err := q.db.Exec(ctx, createNote,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.ProjectID,
	)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
UPDATE notes SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1 AND user_id = $2
`

type DeleteNoteParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) DeleteNote(ctx context.Context, arg DeleteNoteParams) error {
	_, err := q.db.Exec(ctx, deleteNote, arg.ID, arg.UserID)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT j.id, j.title, j.content, j.type, j.source,
       j.created_at, j.updated_at, j.deleted_at, j.archived_at, j.user_id, j.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM notes j
LEFT JOIN projects p ON j.project_id = p.id
WHERE j.id = $1 AND j.user_id = $2
`

type GetNoteByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetNoteByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Type          interface{}        `json:"type"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, arg.ID, arg.UserID)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Type,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ArchivedAt,
		&i.UserID,
		&i.ProjectID,
		&i.ProjectRefID,
		&i.ProjectName,
		&i.ProjectStatus,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT j.id, j.title, j.content, j.type, j.source,
       j.created_at, j.updated_at, j.deleted_at, j.archived_at, j.user_id, j.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM notes j
LEFT JOIN projects p ON j.project_id = p.id
WHERE j.user_id = $1
  AND j.deleted_at IS NULL
  AND ($2::uuid IS NULL OR j.project_id = $2::uuid)
ORDER BY j.updated_at DESC
`

type ListNotesParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.UUID `json:"column_2"`
}

type ListNotesRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Type          interface{}        `json:"type"`
	Source        string             `json:"source"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error) {
	rows, err := q.db.Query(ctx, listNotes, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotesRow
	for rows.Next() {
		var i ListNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ArchivedAt,
			&i.UserID,
			&i.ProjectID,
			&i.ProjectRefID,
			&i.ProjectName,
			&i.ProjectStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNotes = `-- name: SearchNotes :many
SELECT id, title, content, type, source, created_at, updated_at, user_id, project_id, deleted_at, archived_at FROM notes
WHERE user_id = $1 AND deleted_at IS NULL AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC LIMIT 5
`

type SearchNotesParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, searchNotes, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Type,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.ProjectID,
			&i.DeletedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteNotesByProject = `-- name: SoftDeleteNotesByProject :exec
UPDATE notes SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type SoftDeleteNotesByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) SoftDeleteNotesByProject(ctx context.Context, arg SoftDeleteNotesByProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteNotesByProject, arg.ProjectID, arg.UserID)
	return err
}

const updateNote = `-- name: UpdateNote :exec
UPDATE notes SET
    title = COALESCE($3, title),
    content = COALESCE($4, content),
    project_id = CASE WHEN $5::boolean THEN $6::uuid ELSE project_id END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateNoteParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       string      `json:"user_id"`
	Title        string      `json:"title"`
	Content      string      `json:"content"`
	ProjectIDSet bool        `json:"project_id_set"`
	ProjectID    pgtype.UUID `json:"project_id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) error {
	_, err := q.db.Exec(ctx, updateNote,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ProjectIDSet,
		arg.ProjectID,
	)
	return err
}

const upsertNoteFromSync = `-- name: UpsertNoteFromSync :exec
INSERT INTO notes (title, content, user_id, source, type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, title) WHERE deleted_at IS NULL
DO UPDATE SET content = EXCLUDED.content, updated_at = CURRENT_TIMESTAMP
`

type UpsertNoteFromSyncParams struct {
	Title   string      `json:"title"`
	Content string      `json:"content"`
	UserID  string      `json:"user_id"`
	Source  string      `json:"source"`
	Type    interface{} `json:"type"`
}

func (q *Queries) UpsertNoteFromSync(ctx context.Context, arg UpsertNoteFromSyncParams) error {
	_, err := q.db.Exec(ctx, upsertNoteFromSync,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.Source,
		arg.Type,
	)
	return err
}
