// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProject = `-- name: ArchiveProject :one
UPDATE mindmap_project SET status = 'archived', last_updated_by = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND created_by = $2 AND deleted_at IS NULL
RETURNING id, name, description, status, start_date, end_date, created_at, updated_at, created_by, last_updated_by, deleted_at
`

type ArchiveProjectParams struct {
	ID            pgtype.UUID `json:"id"`
	LastUpdatedBy string      `json:"last_updated_by"`
}

func (q *Queries) ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (MindmapProject, error) {
	row := q.db.QueryRow(ctx, archiveProject, arg.ID, arg.LastUpdatedBy)
	var i MindmapProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.LastUpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const countJournalsByProject = `-- name: CountJournalsByProject :one
SELECT COUNT(*)::int FROM mindmap_journal
WHERE project_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type CountJournalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) CountJournalsByProject(ctx context.Context, arg CountJournalsByProjectParams) (int32, error) {
	row := q.db.QueryRow(ctx, countJournalsByProject, arg.ProjectID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO mindmap_project (name, description, status, start_date, end_date, created_by, last_updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, name, description, status, start_date, end_date, created_at, updated_at, created_by, last_updated_by, deleted_at
`

type CreateProjectParams struct {
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Status      interface{} `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   string      `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (MindmapProject, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i MindmapProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.LastUpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, description, status, start_date, end_date, created_at, updated_at, created_by, last_updated_by, deleted_at FROM mindmap_project WHERE id = $1 AND created_by = $2 AND deleted_at IS NULL
`

type GetProjectByIDParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy string      `json:"created_by"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (MindmapProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.CreatedBy)
	var i MindmapProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.LastUpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}

const listGoalStatsByProject = `-- name: ListGoalStatsByProject :many
SELECT id, status FROM mindmap_goal
WHERE project_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type ListGoalStatsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

type ListGoalStatsByProjectRow struct {
	ID     pgtype.UUID `json:"id"`
	Status interface{} `json:"status"`
}

func (q *Queries) ListGoalStatsByProject(ctx context.Context, arg ListGoalStatsByProjectParams) ([]ListGoalStatsByProjectRow, error) {
	rows, err := q.db.Query(ctx, listGoalStatsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalStatsByProjectRow
	for rows.Next() {
		var i ListGoalStatsByProjectRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByProject = `-- name: ListGoalsByProject :many
SELECT id, title, description, status, priority, impact, position, created_at, updated_at, completed_at, deleted_at, user_id, project_id FROM mindmap_goal
WHERE project_id = $1 AND user_id = $2 AND deleted_at IS NULL AND status != 'archived'
ORDER BY position ASC, priority ASC, created_at DESC
`

type ListGoalsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ListGoalsByProject(ctx context.Context, arg ListGoalsByProjectParams) ([]MindmapGoal, error) {
	rows, err := q.db.Query(ctx, listGoalsByProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapGoal
	for rows.Next() {
		var i MindmapGoal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, status, start_date, end_date, created_at, updated_at, created_by, last_updated_by, deleted_at FROM mindmap_project
WHERE created_by = $1 AND deleted_at IS NULL
  AND ($2::boolean OR status != 'archived')
  AND ($3::project_status IS NULL OR status = $3::project_status)
ORDER BY status ASC, created_at DESC
`

type ListProjectsParams struct {
	CreatedBy string      `json:"created_by"`
	Column2   bool        `json:"column_2"`
	Column3   interface{} `json:"column_3"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]MindmapProject, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.CreatedBy, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MindmapProject
	for rows.Next() {
		var i MindmapProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
			&i.LastUpdatedBy,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE mindmap_project SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND created_by = $2
`

type SoftDeleteProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	CreatedBy string      `json:"created_by"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteProject, arg.ID, arg.CreatedBy)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE mindmap_project SET
    name = COALESCE($3, name),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    last_updated_by = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND created_by = $2 AND deleted_at IS NULL
RETURNING id, name, description, status, start_date, end_date, created_at, updated_at, created_by, last_updated_by, deleted_at
`

type UpdateProjectParams struct {
	ID            pgtype.UUID `json:"id"`
	LastUpdatedBy string      `json:"last_updated_by"`
	Name          pgtype.Text `json:"name"`
	Description   pgtype.Text `json:"description"`
	Status        interface{} `json:"status"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (MindmapProject, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.LastUpdatedBy,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i MindmapProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.LastUpdatedBy,
		&i.DeletedAt,
	)
	return i, err
}
