// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveCompletedGoals(ctx context.Context, userID string) (int32, error)
	ArchiveGoalsByProject(ctx context.Context, arg ArchiveGoalsByProjectParams) error
	ArchiveJournalsByProject(ctx context.Context, arg ArchiveJournalsByProjectParams) error
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (MindmapProject, error)
	CheckHabitTitleExists(ctx context.Context, arg CheckHabitTitleExistsParams) (bool, error)
	CheckJournalTitleExists(ctx context.Context, arg CheckJournalTitleExistsParams) (bool, error)
	CompleteOnboarding(ctx context.Context, id string) error
	CountGoals(ctx context.Context, arg CountGoalsParams) (int32, error)
	CountJournals(ctx context.Context, userID string) (int32, error)
	CountJournalsByProject(ctx context.Context, arg CountJournalsByProjectParams) (int32, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) error
	CreateHabit(ctx context.Context, arg CreateHabitParams) error
	CreateJournal(ctx context.Context, arg CreateJournalParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (MindmapProject, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteHabit(ctx context.Context, arg DeleteHabitParams) error
	DeleteJournal(ctx context.Context, arg DeleteJournalParams) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUserRefreshTokens(ctx context.Context, userID string) error
	// Find habit UUIDs mentioned in notes that also mention a given goal.
	// goal_pattern should be like '%data-id="goal:UUID"%'.
	// Returns distinct habit IDs extracted via regex from note content.
	GetConnectedHabitIDs(ctx context.Context, arg GetConnectedHabitIDsParams) ([]pgtype.UUID, error)
	// Find notes/journals whose content contains a mention of the given entity.
	// mention_pattern should be like '%data-id="goal:UUID"%' or '%data-id="habit:UUID"%'.
	GetConnectedNotes(ctx context.Context, arg GetConnectedNotesParams) ([]GetConnectedNotesRow, error)
	GetGoalActivity(ctx context.Context, arg GetGoalActivityParams) ([]GetGoalActivityRow, error)
	GetGoalByID(ctx context.Context, arg GetGoalByIDParams) (GetGoalByIDRow, error)
	GetHabitActivity(ctx context.Context, arg GetHabitActivityParams) ([]pgtype.Timestamptz, error)
	GetHabitByID(ctx context.Context, arg GetHabitByIDParams) (MindmapHabit, error)
	GetHabitTrackerActivity(ctx context.Context, arg GetHabitTrackerActivityParams) ([]pgtype.Date, error)
	// Fetch habits by a list of IDs for a given user.
	GetHabitsByIDs(ctx context.Context, arg GetHabitsByIDsParams) ([]MindmapHabit, error)
	GetJournalActivity(ctx context.Context, arg GetJournalActivityParams) ([]GetJournalActivityRow, error)
	GetJournalByID(ctx context.Context, arg GetJournalByIDParams) (GetJournalByIDRow, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (MindmapProject, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (MindmapRefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (MindmapUser, error)
	GetUserByID(ctx context.Context, id string) (MindmapUser, error)
	ListGoalStatsByProject(ctx context.Context, arg ListGoalStatsByProjectParams) ([]ListGoalStatsByProjectRow, error)
	ListGoals(ctx context.Context, arg ListGoalsParams) ([]ListGoalsRow, error)
	ListGoalsByProject(ctx context.Context, arg ListGoalsByProjectParams) ([]MindmapGoal, error)
	ListHabitTrackerRecords(ctx context.Context, userID string) ([]MindmapHabitTracker, error)
	ListHabits(ctx context.Context, userID string) ([]MindmapHabit, error)
	ListJournals(ctx context.Context, arg ListJournalsParams) ([]ListJournalsRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]MindmapProject, error)
	ListUnassignedGoals(ctx context.Context, userID string) ([]MindmapGoal, error)
	SearchGoals(ctx context.Context, arg SearchGoalsParams) ([]MindmapGoal, error)
	SearchHabits(ctx context.Context, arg SearchHabitsParams) ([]MindmapHabit, error)
	SearchJournals(ctx context.Context, arg SearchJournalsParams) ([]MindmapJournal, error)
	SoftDeleteGoal(ctx context.Context, arg SoftDeleteGoalParams) error
	SoftDeleteGoalsByProject(ctx context.Context, arg SoftDeleteGoalsByProjectParams) error
	SoftDeleteJournalsByProject(ctx context.Context, arg SoftDeleteJournalsByProjectParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error
	TrackHabit(ctx context.Context, arg TrackHabitParams) (pgtype.UUID, error)
	UntrackHabit(ctx context.Context, arg UntrackHabitParams) error
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) error
	UpdateGoalPosition(ctx context.Context, arg UpdateGoalPositionParams) error
	UpdateHabit(ctx context.Context, arg UpdateHabitParams) error
	UpdateJournal(ctx context.Context, arg UpdateJournalParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (MindmapProject, error)
	UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (MindmapUser, error)
	UpsertJournalFromSync(ctx context.Context, arg UpsertJournalFromSyncParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (MindmapUser, error)
}

var _ Querier = (*Queries)(nil)
