// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveCompletedTasks(ctx context.Context, userID string) (int32, error)
	ArchiveNotesByProject(ctx context.Context, arg ArchiveNotesByProjectParams) error
	ArchiveProject(ctx context.Context, arg ArchiveProjectParams) (Project, error)
	ArchiveTasksByProject(ctx context.Context, arg ArchiveTasksByProjectParams) error
	CheckNoteTitleExists(ctx context.Context, arg CheckNoteTitleExistsParams) (bool, error)
	CompleteJob(ctx context.Context, id pgtype.UUID) error
	CompleteOnboarding(ctx context.Context, id string) error
	ConsumeWSTicket(ctx context.Context, tokenHash string) (RefreshToken, error)
	CountContent(ctx context.Context, userID string) (int64, error)
	CountConversations(ctx context.Context, userID string) (int64, error)
	CountMessages(ctx context.Context, conversationID pgtype.UUID) (int64, error)
	CountNotes(ctx context.Context, userID string) (int32, error)
	CountNotesByProject(ctx context.Context, arg CountNotesByProjectParams) (int32, error)
	CountTasks(ctx context.Context, arg CountTasksParams) (int32, error)
	CreateContent(ctx context.Context, arg CreateContentParams) (CreateContentRow, error)
	CreateContentWithExtracted(ctx context.Context, arg CreateContentWithExtractedParams) (CreateContentWithExtractedRow, error)
	CreateConversation(ctx context.Context, userID string) (CreateConversationRow, error)
	CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (User, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (pgtype.UUID, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNote(ctx context.Context, arg CreateNoteParams) error
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error
	// Atomically deletes expired drafts and returns the media_key of each deleted
	// row. Combining SELECT + DELETE into one statement closes the TOCTOU window
	// where a draft could be committed between the two queries, which previously
	// caused us to delete media for a now-committed row.
	DeleteExpiredDraftsReturningKeys(ctx context.Context, updatedAt pgtype.Timestamptz) ([]DeleteExpiredDraftsReturningKeysRow, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteExpiredVerificationTokens(ctx context.Context) error
	DeleteNote(ctx context.Context, arg DeleteNoteParams) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteUserRefreshTokens(ctx context.Context, userID string) error
	DeleteVerificationToken(ctx context.Context, id pgtype.UUID) error
	DeleteVerificationTokensByUserAndType(ctx context.Context, arg DeleteVerificationTokensByUserAndTypeParams) error
	FailJob(ctx context.Context, arg FailJobParams) error
	// Find notes whose content contains a mention of the given entity.
	// mention_pattern should be like '%data-id="task:UUID"%' or '%data-id="note:UUID"%'.
	GetConnectedNotes(ctx context.Context, arg GetConnectedNotesParams) ([]GetConnectedNotesRow, error)
	GetContentByID(ctx context.Context, arg GetContentByIDParams) (GetContentByIDRow, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error)
	GetJobByContentID(ctx context.Context, contentID pgtype.UUID) (Job, error)
	GetMessage(ctx context.Context, id pgtype.UUID) (Message, error)
	GetNoteActivity(ctx context.Context, arg GetNoteActivityParams) ([]GetNoteActivityRow, error)
	GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (GetNoteByIDRow, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTaskActivity(ctx context.Context, arg GetTaskActivityParams) ([]GetTaskActivityRow, error)
	GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (VerificationToken, error)
	GetVerificationTokenByUserAndType(ctx context.Context, arg GetVerificationTokenByUserAndTypeParams) (VerificationToken, error)
	IncrementVerificationAttempts(ctx context.Context, id pgtype.UUID) error
	IsContentDeleted(ctx context.Context, id pgtype.UUID) (bool, error)
	ListContent(ctx context.Context, arg ListContentParams) ([]ListContentRow, error)
	ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error)
	ListNotes(ctx context.Context, arg ListNotesParams) ([]ListNotesRow, error)
	ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error)
	ListTaskStatsByProject(ctx context.Context, arg ListTaskStatsByProjectParams) ([]ListTaskStatsByProjectRow, error)
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]Task, error)
	ListUnassignedTasks(ctx context.Context, userID string) ([]Task, error)
	SearchNotes(ctx context.Context, arg SearchNotesParams) ([]Note, error)
	SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error)
	SetEmailVerified(ctx context.Context, id string) error
	SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error
	SoftDeleteContent(ctx context.Context, arg SoftDeleteContentParams) error
	SoftDeleteConversation(ctx context.Context, arg SoftDeleteConversationParams) error
	SoftDeleteNotesByProject(ctx context.Context, arg SoftDeleteNotesByProjectParams) error
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) error
	SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error
	SoftDeleteTasksByProject(ctx context.Context, arg SoftDeleteTasksByProjectParams) error
	StartJob(ctx context.Context, id pgtype.UUID) error
	TouchConversation(ctx context.Context, id pgtype.UUID) error
	UpdateContentCommitStatus(ctx context.Context, arg UpdateContentCommitStatusParams) error
	UpdateContentEmbedding(ctx context.Context, arg UpdateContentEmbeddingParams) error
	UpdateContentProcessingStatusToPending(ctx context.Context, id pgtype.UUID) error
	UpdateContentResults(ctx context.Context, arg UpdateContentResultsParams) error
	UpdateContentSourceMetadata(ctx context.Context, arg UpdateContentSourceMetadataParams) error
	UpdateContentStatus(ctx context.Context, arg UpdateContentStatusParams) error
	UpdateContentTranscriptSource(ctx context.Context, arg UpdateContentTranscriptSourceParams) error
	UpdateContentVideoFields(ctx context.Context, arg UpdateContentVideoFieldsParams) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) error
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error
	UpdateJobStepResults(ctx context.Context, arg UpdateJobStepResultsParams) error
	UpdateNote(ctx context.Context, arg UpdateNoteParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
	UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error
	UpdateUserAppearance(ctx context.Context, arg UpdateUserAppearanceParams) (User, error)
	UpsertNoteFromSync(ctx context.Context, arg UpsertNoteFromSyncParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
