// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCompletedTasks = `-- name: ArchiveCompletedTasks :one
WITH updated AS (
    UPDATE tasks SET status = 'archived', updated_at = CURRENT_TIMESTAMP
    WHERE user_id = $1 AND status = 'completed'
    RETURNING id
)
SELECT COUNT(*)::int FROM updated
`

func (q *Queries) ArchiveCompletedTasks(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, archiveCompletedTasks, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const archiveTasksByProject = `-- name: ArchiveTasksByProject :exec
UPDATE tasks SET status = 'archived', updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type ArchiveTasksByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) ArchiveTasksByProject(ctx context.Context, arg ArchiveTasksByProjectParams) error {
	_, err := q.db.Exec(ctx, archiveTasksByProject, arg.ProjectID, arg.UserID)
	return err
}

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)::int FROM tasks
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::boolean OR status != 'archived')
  AND ($3::uuid IS NULL OR project_id = $3::uuid)
`

type CountTasksParams struct {
	UserID  string      `json:"user_id"`
	Column2 bool        `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int32, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.UserID, arg.Column2, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (title, description, status, priority, impact, position, user_id, project_id, completed_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateTaskParams struct {
	Title       pgtype.Text        `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      interface{}        `json:"status"`
	Priority    interface{}        `json:"priority"`
	Impact      interface{}        `json:"impact"`
	Position    int32              `json:"position"`
	UserID      string             `json:"user_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.Exec(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Impact,
		arg.Position,
		arg.UserID,
		arg.ProjectID,
		arg.CompletedAt,
	)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT g.id, g.title, g.description, g.status, g.priority, g.impact, g.position,
       g.created_at, g.updated_at, g.completed_at, g.deleted_at, g.user_id, g.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM tasks g
LEFT JOIN projects p ON g.project_id = p.id
WHERE g.id = $1 AND g.user_id = $2
`

type GetTaskByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

type GetTaskByIDRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         pgtype.Text        `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	Priority      interface{}        `json:"priority"`
	Impact        interface{}        `json:"impact"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, arg.ID, arg.UserID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Impact,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.ProjectID,
		&i.ProjectRefID,
		&i.ProjectName,
		&i.ProjectStatus,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT g.id, g.title, g.description, g.status, g.priority, g.impact, g.position,
       g.created_at, g.updated_at, g.completed_at, g.deleted_at, g.user_id, g.project_id,
       p.id as "project_ref_id", p.name as "project_name", p.status as "project_status"
FROM tasks g
LEFT JOIN projects p ON g.project_id = p.id
WHERE g.user_id = $1
  AND g.deleted_at IS NULL
  AND ($2::boolean OR g.status != 'archived')
  AND ($3::uuid IS NULL OR g.project_id = $3::uuid)
ORDER BY g.position ASC, g.priority ASC, g.created_at DESC
`

type ListTasksParams struct {
	UserID  string      `json:"user_id"`
	Column2 bool        `json:"column_2"`
	Column3 pgtype.UUID `json:"column_3"`
}

type ListTasksRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         pgtype.Text        `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Status        interface{}        `json:"status"`
	Priority      interface{}        `json:"priority"`
	Impact        interface{}        `json:"impact"`
	Position      int32              `json:"position"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserID        string             `json:"user_id"`
	ProjectID     pgtype.UUID        `json:"project_id"`
	ProjectRefID  pgtype.UUID        `json:"project_ref_id"`
	ProjectName   pgtype.Text        `json:"project_name"`
	ProjectStatus interface{}        `json:"project_status"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.UserID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
			&i.ProjectRefID,
			&i.ProjectName,
			&i.ProjectStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedTasks = `-- name: ListUnassignedTasks :many
SELECT id, title, description, status, priority, impact, position, created_at, updated_at, completed_at, deleted_at, user_id, project_id FROM tasks
WHERE user_id = $1 AND project_id IS NULL AND deleted_at IS NULL AND status != 'archived'
ORDER BY position ASC, priority ASC, created_at DESC
`

func (q *Queries) ListUnassignedTasks(ctx context.Context, userID string) ([]Task, error) {
	rows, err := q.db.Query(ctx, listUnassignedTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT id, title, description, status, priority, impact, position, created_at, updated_at, completed_at, deleted_at, user_id, project_id FROM tasks
WHERE user_id = $1 AND deleted_at IS NULL AND status != 'archived'
  AND title ILIKE '%' || $2 || '%'
ORDER BY created_at DESC LIMIT 5
`

type SearchTasksParams struct {
	UserID  string      `json:"user_id"`
	Column2 pgtype.Text `json:"column_2"`
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, searchTasks, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Impact,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type SoftDeleteTaskParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID string      `json:"user_id"`
}

func (q *Queries) SoftDeleteTask(ctx context.Context, arg SoftDeleteTaskParams) error {
	_, err := q.db.Exec(ctx, softDeleteTask, arg.ID, arg.UserID)
	return err
}

const softDeleteTasksByProject = `-- name: SoftDeleteTasksByProject :exec
UPDATE tasks SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE project_id = $1 AND user_id = $2
`

type SoftDeleteTasksByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	UserID    string      `json:"user_id"`
}

func (q *Queries) SoftDeleteTasksByProject(ctx context.Context, arg SoftDeleteTasksByProjectParams) error {
	_, err := q.db.Exec(ctx, softDeleteTasksByProject, arg.ProjectID, arg.UserID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    priority = COALESCE($6, priority),
    impact = COALESCE($7, impact),
    position = COALESCE($8, position),
    project_id = CASE WHEN $9::boolean THEN $10::uuid ELSE project_id END,
    completed_at = $11,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateTaskParams struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	Title        pgtype.Text        `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Status       interface{}        `json:"status"`
	Priority     interface{}        `json:"priority"`
	Impact       interface{}        `json:"impact"`
	Position     int32              `json:"position"`
	ProjectIDSet bool               `json:"project_id_set"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.Exec(ctx, updateTask,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.Impact,
		arg.Position,
		arg.ProjectIDSet,
		arg.ProjectID,
		arg.CompletedAt,
	)
	return err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET
    position = $3,
    status = COALESCE($4, status),
    completed_at = CASE
        WHEN $4 = 'completed' THEN CURRENT_TIMESTAMP
        WHEN $4 = 'archived' THEN completed_at
        WHEN $4 IS NOT NULL THEN NULL
        ELSE completed_at
    END,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
`

type UpdateTaskPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   string      `json:"user_id"`
	Position int32       `json:"position"`
	Status   interface{} `json:"status"`
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.Exec(ctx, updateTaskPosition,
		arg.ID,
		arg.UserID,
		arg.Position,
		arg.Status,
	)
	return err
}
