// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE users SET onboarding_completed = true, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) CompleteOnboarding(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeOnboarding, id)
	return err
}

const createEmailUser = `-- name: CreateEmailUser :one
INSERT INTO users (id, name, email, email_verified)
VALUES ($1, $2, $3, NULL)
RETURNING id, name, email, email_verified, image, onboarding_completed, created_at, updated_at, password_hash, theme, font, appearance_template, accent_color, background_color, foreground_color, contrast, font_size, week_start_day, time_format, time_zone, code_font, radius
`

type CreateEmailUserParams struct {
	ID    string      `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email string      `json:"email"`
}

func (q *Queries) CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createEmailUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
		&i.AppearanceTemplate,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ForegroundColor,
		&i.Contrast,
		&i.FontSize,
		&i.WeekStartDay,
		&i.TimeFormat,
		&i.TimeZone,
		&i.CodeFont,
		&i.Radius,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, image, onboarding_completed, created_at, updated_at, password_hash, theme, font, appearance_template, accent_color, background_color, foreground_color, contrast, font_size, week_start_day, time_format, time_zone, code_font, radius FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
		&i.AppearanceTemplate,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ForegroundColor,
		&i.Contrast,
		&i.FontSize,
		&i.WeekStartDay,
		&i.TimeFormat,
		&i.TimeZone,
		&i.CodeFont,
		&i.Radius,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, onboarding_completed, created_at, updated_at, password_hash, theme, font, appearance_template, accent_color, background_color, foreground_color, contrast, font_size, week_start_day, time_format, time_zone, code_font, radius FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
		&i.AppearanceTemplate,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ForegroundColor,
		&i.Contrast,
		&i.FontSize,
		&i.WeekStartDay,
		&i.TimeFormat,
		&i.TimeZone,
		&i.CodeFont,
		&i.Radius,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserAppearance = `-- name: UpdateUserAppearance :one
UPDATE users
SET
    theme = COALESCE($1, theme),
    font = COALESCE($2, font),
    appearance_template = COALESCE($3, appearance_template),
    accent_color = COALESCE($4, accent_color),
    background_color = COALESCE($5, background_color),
    foreground_color = COALESCE($6, foreground_color),
    contrast = COALESCE($7, contrast),
    font_size = COALESCE($8, font_size),
    code_font = COALESCE($9, code_font),
    radius = COALESCE($10, radius),
    week_start_day = COALESCE($11, week_start_day),
    time_format = COALESCE($12, time_format),
    time_zone = COALESCE($13, time_zone),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $14
RETURNING id, name, email, email_verified, image, onboarding_completed, created_at, updated_at, password_hash, theme, font, appearance_template, accent_color, background_color, foreground_color, contrast, font_size, week_start_day, time_format, time_zone, code_font, radius
`

type UpdateUserAppearanceParams struct {
	Theme              pgtype.Text `json:"theme"`
	Font               pgtype.Text `json:"font"`
	AppearanceTemplate pgtype.Text `json:"appearance_template"`
	AccentColor        pgtype.Text `json:"accent_color"`
	BackgroundColor    pgtype.Text `json:"background_color"`
	ForegroundColor    pgtype.Text `json:"foreground_color"`
	Contrast           pgtype.Int4 `json:"contrast"`
	FontSize           pgtype.Int4 `json:"font_size"`
	CodeFont           pgtype.Text `json:"code_font"`
	Radius             pgtype.Int4 `json:"radius"`
	WeekStartDay       pgtype.Text `json:"week_start_day"`
	TimeFormat         pgtype.Text `json:"time_format"`
	TimeZone           pgtype.Text `json:"time_zone"`
	ID                 string      `json:"id"`
}

func (q *Queries) UpdateUserAppearance(ctx context.Context, arg UpdateUserAppearanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAppearance,
		arg.Theme,
		arg.Font,
		arg.AppearanceTemplate,
		arg.AccentColor,
		arg.BackgroundColor,
		arg.ForegroundColor,
		arg.Contrast,
		arg.FontSize,
		arg.CodeFont,
		arg.Radius,
		arg.WeekStartDay,
		arg.TimeFormat,
		arg.TimeZone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
		&i.AppearanceTemplate,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ForegroundColor,
		&i.Contrast,
		&i.FontSize,
		&i.WeekStartDay,
		&i.TimeFormat,
		&i.TimeZone,
		&i.CodeFont,
		&i.Radius,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, name, email, image, email_verified)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = COALESCE(EXCLUDED.name, users.name),
    image = COALESCE(EXCLUDED.image, users.image),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, email, email_verified, image, onboarding_completed, created_at, updated_at, password_hash, theme, font, appearance_template, accent_color, background_color, foreground_color, contrast, font_size, week_start_day, time_format, time_zone, code_font, radius
`

type UpsertUserParams struct {
	ID    string      `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email string      `json:"email"`
	Image pgtype.Text `json:"image"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
		&i.AppearanceTemplate,
		&i.AccentColor,
		&i.BackgroundColor,
		&i.ForegroundColor,
		&i.Contrast,
		&i.FontSize,
		&i.WeekStartDay,
		&i.TimeFormat,
		&i.TimeZone,
		&i.CodeFont,
		&i.Radius,
	)
	return i, err
}
