// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOnboarding = `-- name: CompleteOnboarding :exec
UPDATE users SET onboarding_completed = true, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) CompleteOnboarding(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, completeOnboarding, id)
	return err
}

const createEmailUser = `-- name: CreateEmailUser :one
INSERT INTO users (id, name, email, email_verified)
VALUES ($1, $2, $3, NULL)
RETURNING id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font
`

type CreateEmailUserParams struct {
	ID    string      `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email string      `json:"email"`
}

func (q *Queries) CreateEmailUser(ctx context.Context, arg CreateEmailUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createEmailUser, arg.ID, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}

const setEmailVerified = `-- name: SetEmailVerified :exec
UPDATE users SET email_verified = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) SetEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setEmailVerified, id)
	return err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type SetPasswordHashParams struct {
	ID           string      `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserAppearance = `-- name: UpdateUserAppearance :one
UPDATE users
SET
    theme = COALESCE($1, theme),
    font = COALESCE($2, font),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $3
RETURNING id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font
`

type UpdateUserAppearanceParams struct {
	Theme pgtype.Text `json:"theme"`
	Font  pgtype.Text `json:"font"`
	ID    string      `json:"id"`
}

func (q *Queries) UpdateUserAppearance(ctx context.Context, arg UpdateUserAppearanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAppearance, arg.Theme, arg.Font, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}

const updateUserXP = `-- name: UpdateUserXP :one
UPDATE users SET xp = xp + $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font
`

type UpdateUserXPParams struct {
	ID string `json:"id"`
	Xp int32  `json:"xp"`
}

func (q *Queries) UpdateUserXP(ctx context.Context, arg UpdateUserXPParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserXP, arg.ID, arg.Xp)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, name, email, image, email_verified)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE SET
    name = COALESCE(EXCLUDED.name, users.name),
    image = COALESCE(EXCLUDED.image, users.image),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, name, email, email_verified, image, xp, onboarding_completed, created_at, updated_at, password_hash, theme, font
`

type UpsertUserParams struct {
	ID    string      `json:"id"`
	Name  pgtype.Text `json:"name"`
	Email string      `json:"email"`
	Image pgtype.Text `json:"image"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Image,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.Xp,
		&i.OnboardingCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
		&i.Theme,
		&i.Font,
	)
	return i, err
}
