// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO mindmap_verification_token (user_id, token_hash, type, password_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateVerificationTokenParams struct {
	UserID       string             `json:"user_id"`
	TokenHash    string             `json:"token_hash"`
	Type         string             `json:"type"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.PasswordHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredVerificationTokens = `-- name: DeleteExpiredVerificationTokens :exec
DELETE FROM mindmap_verification_token WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredVerificationTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredVerificationTokens)
	return err
}

const deleteVerificationToken = `-- name: DeleteVerificationToken :exec
DELETE FROM mindmap_verification_token WHERE id = $1
`

func (q *Queries) DeleteVerificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationToken, id)
	return err
}

const deleteVerificationTokensByUserAndType = `-- name: DeleteVerificationTokensByUserAndType :exec
DELETE FROM mindmap_verification_token WHERE user_id = $1 AND type = $2
`

type DeleteVerificationTokensByUserAndTypeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) DeleteVerificationTokensByUserAndType(ctx context.Context, arg DeleteVerificationTokensByUserAndTypeParams) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensByUserAndType, arg.UserID, arg.Type)
	return err
}

const getVerificationToken = `-- name: GetVerificationToken :one
SELECT id, user_id, token_hash, type, password_hash, attempts, expires_at, created_at FROM mindmap_verification_token
WHERE token_hash = $1 AND type = $2 AND expires_at > CURRENT_TIMESTAMP
`

type GetVerificationTokenParams struct {
	TokenHash string `json:"token_hash"`
	Type      string `json:"type"`
}

func (q *Queries) GetVerificationToken(ctx context.Context, arg GetVerificationTokenParams) (MindmapVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationToken, arg.TokenHash, arg.Type)
	var i MindmapVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.PasswordHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationTokenByUserAndType = `-- name: GetVerificationTokenByUserAndType :one
SELECT id, user_id, token_hash, type, password_hash, attempts, expires_at, created_at FROM mindmap_verification_token
WHERE user_id = $1 AND type = $2 AND expires_at > CURRENT_TIMESTAMP
`

type GetVerificationTokenByUserAndTypeParams struct {
	UserID string `json:"user_id"`
	Type   string `json:"type"`
}

func (q *Queries) GetVerificationTokenByUserAndType(ctx context.Context, arg GetVerificationTokenByUserAndTypeParams) (MindmapVerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByUserAndType, arg.UserID, arg.Type)
	var i MindmapVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.PasswordHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :exec
UPDATE mindmap_verification_token SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementVerificationAttempts, id)
	return err
}
