FROM golang:1.25-alpine

RUN apk --no-cache add ffmpeg python3 py3-pip \
    && pip3 install --break-system-packages yt-dlp
RUN go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080
CMD ["sh", "-c", "go mod tidy && air -c .air.toml"]
