ALTER TABLE users
  ADD COLUMN appearance_template VARCHAR(32) NOT NULL DEFAULT 'codex',
  ADD COLUMN accent_color VARCHAR(16) NOT NULL DEFAULT '#60AACC',
  ADD COLUMN background_color VARCHAR(16) NOT NULL DEFAULT '#0F0F11',
  ADD COLUMN foreground_color VARCHAR(16) NOT NULL DEFAULT '#E3E4E6',
  ADD COLUMN contrast INTEGER NOT NULL DEFAULT 82,
  ADD COLUMN font_size INTEGER NOT NULL DEFAULT 14,
  ADD COLUMN glass_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN glass_opacity INTEGER NOT NULL DEFAULT 70,
  ADD COLUMN week_start_day VARCHAR(16) NOT NULL DEFAULT 'monday',
  ADD COLUMN time_format VARCHAR(8) NOT NULL DEFAULT '12h',
  ADD COLUMN time_zone VARCHAR(64) NOT NULL DEFAULT 'auto',
  ADD CONSTRAINT users_appearance_template_check CHECK (appearance_template IN ('codex', 'linear', 'github', 'notion', 'raycast', 'system')),
  ADD CONSTRAINT users_accent_color_check CHECK (accent_color ~ '^#[0-9A-Fa-f]{6}$'),
  ADD CONSTRAINT users_background_color_check CHECK (background_color ~ '^#[0-9A-Fa-f]{6}$'),
  ADD CONSTRAINT users_foreground_color_check CHECK (foreground_color ~ '^#[0-9A-Fa-f]{6}$'),
  ADD CONSTRAINT users_contrast_check CHECK (contrast BETWEEN 0 AND 100),
  ADD CONSTRAINT users_font_size_check CHECK (font_size BETWEEN 12 AND 20),
  ADD CONSTRAINT users_glass_opacity_check CHECK (glass_opacity BETWEEN 0 AND 100),
  ADD CONSTRAINT users_week_start_day_check CHECK (week_start_day IN ('monday', 'sunday', 'saturday')),
  ADD CONSTRAINT users_time_format_check CHECK (time_format IN ('12h', '24h'));
